CONFIG_ZMK_KEYBOARD_NAME="Fish Keyboard"

# deep sleepを使わない
CONFIG_ZMK_SLEEP=n

# 通常運用ではUSB loggingを切る
CONFIG_ZMK_USB_LOGGING=n

# split + ホストBLE 1台ぶんだけ残す
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2

CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=5
